name: Feature request
description: Suggest an idea for this project
title: '[Feature]: '
labels:
  - enhancement
body:
  - type: input
    id: featureName
    attributes:
      label: Feature name
    validations:
      required: true
  - type: textarea
    id: featureContent
    attributes:
      label: Explain the feature 
      description: Tell us what we should add
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: I read the Code Of Conduct
      options:
        - label: I read the Code Of Conduct and I comply to it
          required: true
