name: KapEngine Build

on:
  push:
    branches: [ main ]
  delete:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      steps:
      - uses: actions/checkout@v3

      - name: Creation build area
        run: rm -rf build && mkdir build

      - name: Go to build area
        run: cd build

      - name: Check build
        run: cmake .. && make
